### ISSUE TITLE
Install package with `CREATE FUNCTION`

### ISSUE THREAD

**Issue by matzeeable** [snapcreek/duplicator#404]
Hey Duplicator team!

One of my customers had recently issues with the installation of a Duplicator package. The cause is that my plugin (https://wordpress.org/plugins/real-media-library-lite/) is using an UDF in database which is created as follow (you can ignore the body of the function as it simply prepares some data):

```php
<?php
// [...]
$function_name = $wpdb->prefix . 'fn_realmedialibrary_childs';
$wpdb->query("DROP FUNCTION IF EXISTS $function_name");
$sql =
    "CREATE FUNCTION $function_name(rootId INT, _useTempChildTableForCheck BOOLEAN) RETURNS varchar(1000) SQL SECURITY INVOKER BEGIN
	DECLARE sTemp VARCHAR(1000);
	DECLARE sTempChd VARCHAR(1000);
	SET sTemp = '$';
	SET sTempChd = CAST(rootId AS CHAR);
    SET SESSION group_concat_max_len = 100000;
	WHILE sTempChd IS NOT NULL DO
		SET sTemp = CONCAT(sTemp,',',sTempChd);
		IF _useTempChildTableForCheck IS NULL OR _useTempChildTableForCheck = false THEN
		    SELECT GROUP_CONCAT(id) INTO sTempChd FROM $table_name WHERE FIND_IN_SET(parent,sTempChd) > 0;
		ELSE
		    SELECT GROUP_CONCAT(id) INTO sTempChd FROM " .
    $this->getTableName('tmp') .
    ' WHERE FIND_IN_SET(parent,sTempChd) > 0;
		END IF;
	END WHILE;
	RETURN sTemp;
END';

$wpdb->query($sql);
```

Duplicator logs the following error (truncated):

```
--------------------------------------
DATABASE-ENVIRONMENT
--------------------------------------
MYSQL VERSION:	This Server: 5.7.29 -- Build Server: 5.7.29
FILE SIZE:	dup-database__[HASH].sql (16.3MB)
TIMEOUT:	5000
MAXPACK:	67108864
SQLMODE:	NOT_SET
NEW SQL FILE:	[/html/bw/dup-installer/dup-installer-data__[HASH].sql]
COLLATE FB:	Off
--------------------------------------
DATABASE RESULTS
--------------------------------------
Skipping delimiter query
**ERROR** database error write 'Access denied; you need (at least one of) the SUPER privilege(s) for this operation' - [sql=CREATE DEFINER=`xxxxxxx`@`xxxxxx.xxxxxx.com` FUNCTION `bwwp_fn_rea...]
DB VIEWS:	enabled
DB PROCEDURES:	enabled
ERRORS FOUND:	1
DROPPED TABLES:	0
RENAMED TABLES:	0
QUERIES RAN:	516
```

The main error message is: **Access denied; you need (at least one of) the SUPER privilege(s) for this operation**. I did further research and stumbled over this answer: https://stackoverflow.com/a/44015870/5506547 

**How can it be solved?**

> Either remove the DEFINER=.. statement from your sqldump file, or replace the user values with CURRENT_USER. 
> The MySQL server provided by RDS does not allow a DEFINER syntax for another user (in my experience).

Simply remove the `DEFINER` statement from the `CREATE FUNCTION` and it is solved.

I had a look at the coding of Duplicator, currently, you are doing the following things:

- Replace all `DEFINER` with the current used user: https://github.com/snapcreek/duplicator/blob/0a129dcd98f0d5587f14daf75a124a2e24141ce8/installer/dup-installer/ctrls/ctrl.s2.dbinstall.php#L77 - but as stated above, the MySQL server provided by RDS does not allow a DEFINER syntax for another user
- You have defined a `applyProcUserFix` function which seems to do the correct thing and removes all the `DEFINER` statements, but you are not using it in any of your codings: https://github.com/snapcreek/duplicator/blob/0a129dcd98f0d5587f14daf75a124a2e24141ce8/installer/dup-installer/ctrls/ctrl.s2.dbinstall.php#L582-L591

What can I do to remove the `DEFINER` statement, so the installation works without any errors? Do you provide any hook for this?

Regards,
Matthew 😊

**Comment by lifeinthegrid** [comment]
Hey @matzeeable, 

Thanks for the detailed write-up!  We don't have any hooks available at the moment.  I'll try and get you out a hotfix for this sometime this week...

Thxs~

**Comment by matzeeable** [comment]
Hi @lifeinthegrid !

Thanks for your reply.

Do you need any help from me?

Regards
Matthew :-)

**Comment by meistertigran** [comment]
Hi @matzeeable,

I have attached a patched version of Duplicator to this message which I think should resolve the issue. 

Please try it out and let me know how it goes.

Thanks!
Tigran.
[duplicator-patched.zip](https://github.com/snapcreek/duplicator/files/5841845/duplicator-patched.zip)

**Comment by matzeeable** [comment]
Hey @meistertigran !

Thanks for the patch. I just sent it to my customer, I will let you know asap if it works!

Regards,
Matthew :-)

**Comment by matzeeable** [comment]
Hey @meistertigran !

Me again and sorry for the delayed answer. My customer just replied to me and he says, he still get's the following error:

```
**ERROR** database error write 'Access denied; you need (at least one of) the SUPER privilege(s) for this operation' - [sql=CREATE DEFINER=`p544295d41`@`%` FUNCTION `wp_fn_realmedialibrary_childs`(...]
```

Shouldn't your last patch remove the `DEFINER` clause from functions and procedures? As you can read from this thread, it simply should be removed: https://stackoverflow.com/a/44015870/5506547

Regards,
Matthew :-)

**Comment by meistertigran** [comment]
Hey @matzeeable 

Sorry for the delay. We thought the issue might be with the way the host was specified in the definer (since remote hosts have to be replaced by %) but seems like that was not the actual issue. 

Attached is a patch with a new option at Step 2 of the installation process (screenshot) which will allow you to remove the definer from queries. 

![image](https://user-images.githubusercontent.com/16627927/107355569-165c3d00-6ae9-11eb-8b0b-8ae3aee71fba.png)

Please let me know if this patch works for you.
Thanks,
Tigran

[duplicator-definer-patch.zip](https://github.com/snapcreek/duplicator/files/5950947/duplicator-definer-patch.zip)

**Comment by matzeeable** [comment]
Hey @meistertigran !

Thanks for the patched version. It works now as expected! :-)

And, I should tell you a thank you from my client, great job and thanks for the cooperation!

Ticket can be closed by you, when released.

Regards,
Matthew 😊

**Comment by lifeinthegrid** [comment]
Thanks for the update Matthew!  This fix should roll out in 1.4.0.
